#Welcome to the AlwaysOnline main configuration file!

#The delay to wait between checking to see if mojang is online, in seconds.
check-interval: 120

#
# 1 = Multifile: All information will be stored in a lot of small files in a directory, indexed by name
# 2 = Mysql: Stores all information in a MySql database
#
database-type: 1

#How many times should we check to confirm if the session servers are down?
down-amount: 2
# "I would add a setting for how many times to check before we call the session servers offline.
#  Like check 5 times, every second defined in check-interval, and if they are down on all times declare the session servers offline." - jeff142

#Set this to true if you want AlwaysOnline to go in mojang offline mode when the servers have a slow response.
offline-quite-slow: false

#Message to broadcast when mojang servers are offline. Set to null to disable.

message-broadcast-offline: '&c&lMojang servers are offline! However you can still login from the same computer to get back on!'

#Message to broadcast when mojang servers are online. Set to null to disable.

message-broadcast-online: '&c&lMojang servers are back online and all services are now normal again!'

#Message for the MOTD to be when mojang servers are offline. Set to null to disable.
message-motd-offline: '&eMojang servers are down,.newline.&ebut you can still connect!'

#The message to display when a user attempts to login while the mojang servers are offline, but their IP does not match.
message-kick-ip: 'We can not let you in since you are not on the same computer you logged on before!'

#The message to display when a user is new and logs in while mojang servers are offline.
message-kick-new: 'We can not let you login because the mojang servers are offline!'

#The message to display when a user attempts to login with a non-valid minecraft username.
message-kick-invalid: 'Invalid username. Hacking?'

#Set this to true for extra messages used for debugging
debug: false

##########################################
#    Mysql Database Information
#    Only edit if using mysql
##########################################

host: 127.0.0.1

port: 3306

database-name: 'server_database'

database-username: 'root'

database-password: 'password'

#Don't change this please!
config_version: 3