#Welcome to the AlwaysOnline main configuration file!

#
# 1 = Check the url http://status.mojang.com/check?service=session.minecraft.net to see if they are offline (recommended)
# 2 = Do a direct ping test to the session servers
# 3 = Use http://xpaw.ru/mcstatus to determine if the session service is down
#
session-check-mode: 1

#The delay to wait between checking to see if mojang is online, in seconds.
check-interval: 120

#
# 1 = Multifile: All information will be stored in a lot of small files in a directory, indexed by name
# 2 = Mysql: Stores all information in a MySql database
#
database-type: 1

#Message to broadcast when mojang servers are offline. Set to null to disable.

message-broadcast-offline: '&c&lMojang servers are offline! However you can still login from the same computer to get back on!'

#Message to broadcast when mojang servers are online. Set to null to disable.

message-broadcast-online: '&c&lMojang servers are back online and all services are now normal again!'

#Message for the MOTD to be when mojang servers are offline. Set to null to disable.
message-motd-offline: '&eMojang servers are down,.newline.&ebut you can still connect!'

##########################################
#    Mysql Database Information
#    Only edit if using mysql
##########################################

host: 127.0.0.1

port: 3306

database-name: 'server_database'

database-username: 'root'

database-password: 'password'