name: AlwaysOnline
version: 6.0
main: me.johnnywoof.spigot.AlwaysOnline
author: Johnnywoof
website: http://www.spigotmc.org/resources/alwaysonline.820/
softdepend: [ProtocolLib]
commands:
    alwaysonline:
        description: Base command for always online.
        permission: alwaysonline.usage
        usage: /alwaysonline
        aliases: [ao]
