name: AlwaysOnline
version: 5.2
main: me.johnnywoof.spigot.AlwaysOnline
author: Johnnywoof
commands:
    alwaysonline:
        description: Base command for always online.
        usage: /alwaysonline
        aliases: [ao]
