name: AlwaysOnline
version: 2.0.9
main: me.johnnywoof.spigot.AlwaysOnline
author: johnnywoof
commands:
    alwaysonline:
        description: AlwaysOnline command
        usage: /ao
        aliases: [ao]